# ------ dataset_path ------
data_path: '/data16/Public/Datasets/dtd/'

# ------ Hyperparamters ------
alpha: 0.5
search_low: 0
search_high: 1
search_step: 50

# ------ Basic Config ------
dataset: 'dtd'
shots: 16
backbone: 'RN50' # RN50 RN101 ViT-B/32 ViT-B/16

lr: 0.0001
train_epoch: 50
batch_size: 64

num_classes: 47

num_threads: 8
save_interval: 10

cache_dir: './model/clip'
